# Generated by Django 4.2.2 on 2023-06-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_report_summary', models.TextField(max_length=200)),
                ('activity_report_hoursPerWeek', models.FloatField()),
                ('activity_report_hoursPerWeekIntersemester', models.FloatField()),
                ('activity_report_conclusion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_repot_id', models.CharField(max_length=50)),
                ('evidence_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_degree', models.TextField(max_length=200)),
                ('professor_names', models.TextField(max_length=200)),
                ('professor_lastnames', models.TextField(max_length=200)),
                ('professor_denomination', models.TextField(max_length=200)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.career')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.professor')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.school')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.career')),
                ('coordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.professor')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.TextField(max_length=200)),
                ('report_uploadDate', models.DateField()),
                ('report_professorComment', models.TextField(max_length=200)),
                ('report_revisorComment', models.TextField(max_length=200)),
                ('report_isApproved', models.BooleanField(default=False)),
                ('report_pathToFile', models.TextField(max_length=200)),
                ('activity_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.activity_report', verbose_name='General Activities')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.professor')),
                ('report_approvedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester_school')),
                ('report_reviewedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester_career')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_comment', models.TextField(blank=True)),
                ('document_uploadDate', models.DateField()),
                ('document_pathToFile', models.TextField(max_length=200)),
                ('activity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.activity_type')),
                ('evidence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.evidence')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.professor')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.school'),
        ),
        migrations.AddField(
            model_name='activity_report',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.professor'),
        ),
        migrations.AddField(
            model_name='activity_report',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester'),
        ),
    ]
