# Generated by Django 4.2.2 on 2023-07-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_report_management',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_management',
            name='professor_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_management',
            name='semester_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_teaching',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_teaching',
            name='professor_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_teaching',
            name='semester_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_vinculation',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_vinculation',
            name='professor_id',
        ),
        migrations.RemoveField(
            model_name='activity_report_vinculation',
            name='semester_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='activity_report_investigation_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='activity_report_management_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='activity_report_teaching_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='activity_report_vinculation_id',
        ),
        migrations.AddField(
            model_name='report',
            name='investigation_report_hoursPerWeek',
            field=models.FloatField(default=2.6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='investigation_report_hoursPerWeekIntersemester',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='investigation_report_summary',
            field=models.TextField(default=2.5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='management_report_hoursPerWeek',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='management_report_hoursPerWeekIntersemester',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='management_report_summary',
            field=models.TextField(default=2.5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='teaching_report_hoursPerWeek',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='teaching_report_hoursPerWeekIntersemester',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='teaching_report_summary',
            field=models.TextField(default='El resumen', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='vinculation_report_hoursPerWeekIntersemester',
            field=models.FloatField(default=2.8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='vinculation_report_summary',
            field=models.TextField(default='El resumen', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='vinculationt_report_hoursPerWeek',
            field=models.FloatField(default=6.7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Activity_Report_Investigation',
        ),
        migrations.DeleteModel(
            name='Activity_Report_Management',
        ),
        migrations.DeleteModel(
            name='Activity_Report_Teaching',
        ),
        migrations.DeleteModel(
            name='Activity_Report_Vinculation',
        ),
    ]
