# Generated by Django 4.2.2 on 2023-06-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_abbreviation',
            field=models.TextField(default=models.TextField(max_length=200), max_length=200),
        ),
    ]
