# Generated by Django 4.2.1 on 2023-07-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0002_remove_activity_report_management_document_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
