# Generated by Django 4.2.2 on 2023-06-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0002_school_school_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_abbreviation',
            field=models.TextField(max_length=200),
        ),
    ]
