# Generated by Django 4.2.2 on 2023-06-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0004_semester_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
