# Generated by Django 4.2.2 on 2023-06-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0005_alter_semester_semester_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evidence',
            new_name='Evidence_Type',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semester_name',
        ),
    ]
