# Generated by Django 4.2.2 on 2023-06-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0006_rename_evidence_evidence_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_abbreviation',
        ),
    ]
