# Generated by Django 3.1.4 on 2023-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0006_auto_20230712_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploadedDocument',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
