# Generated by Django 4.2.2 on 2023-06-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0007_remove_school_school_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_abbreviation',
            field=models.TextField(default=models.TextField(max_length=200), max_length=200),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_name',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
