# Generated by Django 4.2.2 on 2023-06-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0008_school_school_abbreviation_semester_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semester_name',
        ),
    ]
