# Generated by Django 3.1.4 on 2023-07-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0009_remove_document_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploadedDocument',
            field=models.FileField(default='file', upload_to=''),
            preserve_default=False,
        ),
    ]
