# Generated by Django 3.1.4 on 2023-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0010_document_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedDocument',
            field=models.FileField(upload_to='media/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
