# Generated by Django 4.2.2 on 2023-06-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0010_semester_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence_type',
            name='activity_repot_id',
        ),
        migrations.AddField(
            model_name='evidence_type',
            name='activity_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.activity_type'),
        ),
    ]
