# Generated by Django 4.2.2 on 2023-06-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0011_remove_evidence_type_activity_repot_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='activity_type_id',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='evidence_id',
            new_name='evidence_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_uploadDate',
            field=models.DateField(auto_now=True),
        ),
    ]
