# Generated by Django 3.1.4 on 2023-07-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0012_auto_20230713_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedDocument',
            field=models.FileField(upload_to='0302616099'),
        ),
    ]
