# Generated by Django 4.2.2 on 2023-06-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0012_rename_activity_type_id_document_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_report',
            name='document_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_uploadDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evidence_type',
            name='evidence_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='report',
            name='activity_report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.activity_report'),
        ),
    ]
