# Generated by Django 4.2.2 on 2023-06-27 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0013_activity_report_document_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_report',
            name='document_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.document'),
        ),
    ]
