# Generated by Django 3.1.4 on 2023-07-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0014_auto_20230713_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_comment',
        ),
        migrations.AddField(
            model_name='document',
            name='document_professorComment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='document_revisorComment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.professor'),
        ),
    ]
