# Generated by Django 3.1.4 on 2023-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0015_auto_20230714_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='isDean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='isRevisor',
            field=models.BooleanField(default=False),
        ),
    ]
