# Generated by Django 3.1.4 on 2023-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0016_auto_20230719_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_professorComment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_revisorComment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
