# Generated by Django 4.2.2 on 2023-06-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0016_activity_report_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_report',
            name='document_id',
        ),
    ]
