# Generated by Django 3.1.4 on 2023-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0017_auto_20230720_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_approved',
            field=models.BooleanField(default=False),
        ),
    ]
