# Generated by Django 4.2.2 on 2023-06-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0017_remove_activity_report_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_report',
            name='document_id',
            field=models.ForeignKey(default=int(1), on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.document'),
        ),
        migrations.AlterField(
            model_name='evidence_type',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.activity_type'),
        ),
    ]
