# Generated by Django 3.1.4 on 2023-07-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0018_document_document_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
