# Generated by Django 3.1.4 on 2023-07-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0019_auto_20230724_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_approved',
            field=models.BooleanField(null=True),
        ),
    ]
