# Generated by Django 3.1.4 on 2023-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0021_remove_document_document_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_isReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
