# Generated by Django 3.1.4 on 2023-07-28 07:43

from django.db import migrations, models
import professor_evidence.models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0022_report_report_isreviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedDocument',
            field=models.FileField(max_length=500, upload_to=professor_evidence.models.Document.get_document_upload_path),
        ),
    ]
