# Generated by Django 3.1.4 on 2023-07-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0023_auto_20230728_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence_type',
            name='evidence_code',
            field=models.CharField(default=' ', max_length=5),
        ),
    ]
