# Generated by Django 3.1.4 on 2023-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0024_evidence_type_evidence_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence_type',
            name='evidence_code',
            field=models.CharField(max_length=5),
        ),
    ]
