# Generated by Django 3.1.4 on 2023-07-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0025_auto_20230728_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_pathToFile',
        ),
    ]
