# Generated by Django 3.1.4 on 2023-07-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0027_report_uploadedreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='uploadedReport',
        ),
    ]
