# Generated by Django 3.1.4 on 2023-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0028_remove_report_uploadedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uploadedReport',
            field=models.FileField(blank=True, max_length=500, upload_to='report_pdfs'),
        ),
    ]
