# Generated by Django 3.1.4 on 2023-07-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0029_report_uploadedreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='vinculationt_report_hoursPerWeek',
            new_name='vinculation_report_hoursPerWeek',
        ),
    ]
