# Generated by Django 3.1.4 on 2023-07-30 16:23

from django.db import migrations, models
import professor_evidence.models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0031_auto_20230729_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='investigation_report_summary',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='management_report_summary',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_conclusion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_professorComment',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_revisorComment',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_uploadDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='teaching_report_summary',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='uploadedReport',
            field=models.FileField(blank=True, max_length=500, upload_to=professor_evidence.models.Report.get_report_upload_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='vinculation_report_summary',
            field=models.TextField(max_length=500),
        ),
    ]
