# Generated by Django 3.1.4 on 2023-07-30 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0032_auto_20230730_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='isCurrentSemester',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_approvedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester_school'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_reviewedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor_evidence.semester_career'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.TextField(default='SEM', max_length=200),
        ),
    ]
