# Generated by Django 3.1.4 on 2023-07-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0034_auto_20230731_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_uploadDate',
            field=models.DateField(auto_now=True),
        ),
    ]
