# Generated by Django 3.1.4 on 2023-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0035_auto_20230731_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_uploadDate',
            field=models.DateField(),
        ),
    ]
