# Generated by Django 3.1.4 on 2023-07-31 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0036_auto_20230731_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_uploadDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
