# Generated by Django 3.1.4 on 2023-08-02 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professor_evidence', '0040_auto_20230801_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_uploadDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
