# Generated by Django 3.1.4 on 2023-07-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230724_0304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
