# Generated by Django 3.1.4 on 2023-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20230712_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ci',
            field=models.CharField(default='', max_length=10),
        ),
    ]
